package create

import (
	"encoding/json"
	"fmt"

	"github.com/MakeNowJust/heredoc/v2"
	"github.com/spf13/cobra"

	gitlab "gitlab.com/gitlab-org/api/client-go/v2"

	"gitlab.com/gitlab-org/cli/internal/api"
	"gitlab.com/gitlab-org/cli/internal/cmdutils"
	"gitlab.com/gitlab-org/cli/internal/glrepo"
	"gitlab.com/gitlab-org/cli/internal/iostreams"
	"gitlab.com/gitlab-org/cli/internal/mcpannotations"
)

type options struct {
	apiClient func(repoHost string) (*api.Client, error)
	io        *iostreams.IOStreams
	baseRepo  func() (glrepo.Interface, error)

	group        string
	name         string
	username     string
	email        string
	outputFormat string
}

func NewCmdCreate(f cmdutils.Factory) *cobra.Command {
	opts := &options{
		io:        f.IO(),
		apiClient: f.ApiClient,
		baseRepo:  f.BaseRepo,
	}

	cmd := &cobra.Command{
		Use:   "create [flags]",
		Short: "Create a service account in a group.",
		Long: heredoc.Doc(`
			Create a new service account in a group. The name, username,
			and email are optional and will be auto-generated by GitLab
			if not specified.

			This API endpoint works on top-level groups only. It does not
			work on subgroups.
		`),
		Example: heredoc.Doc(`
		# Create a service account with auto-generated attributes
		glab service-account create --group my-group

		# Create a service account with a specific name
		glab service-account create --group my-group --name "CI Bot"

		# Create a service account with all attributes specified
		glab service-account create --group my-group --name "CI Bot" --username ci-bot --email ci-bot@example.com`),
		Annotations: map[string]string{
			mcpannotations.Exclude: "true",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := opts.complete(cmd); err != nil {
				return err
			}

			if err := opts.validate(); err != nil {
				return err
			}

			return opts.run()
		},
	}

	cmdutils.EnableRepoOverride(cmd, f)
	cmd.Flags().StringVarP(&opts.group, "group", "g", "", "The group to create the service account in (required).")
	cmd.Flags().StringVar(&opts.name, "name", "", "Name of the service account.")
	cmd.Flags().StringVar(&opts.username, "username", "", "Username of the service account.")
	cmd.Flags().StringVar(&opts.email, "email", "", "Email of the service account.")
	cmdutils.EnableJSONOutput(cmd, &opts.outputFormat, "Format output as: text, json.")
	return cmd
}

func (o *options) complete(cmd *cobra.Command) error {
	group, err := cmdutils.GroupOverride(cmd)
	if err != nil {
		return err
	}
	o.group = group
	return nil
}

func (o *options) validate() error {
	if o.group == "" {
		return cmdutils.FlagError{Err: fmt.Errorf("the required flag '--group' is not set")}
	}
	return nil
}

func (o *options) run() error {
	var repoHost string
	if baseRepo, err := o.baseRepo(); err == nil {
		repoHost = baseRepo.RepoHost()
	}
	apiClient, err := o.apiClient(repoHost)
	if err != nil {
		return err
	}
	client := apiClient.Lab()

	createOpts := &gitlab.CreateServiceAccountOptions{}
	if o.name != "" {
		createOpts.Name = &o.name
	}
	if o.username != "" {
		createOpts.Username = &o.username
	}
	if o.email != "" {
		createOpts.Email = &o.email
	}

	sa, _, err := client.Groups.CreateServiceAccount(o.group, createOpts)
	if err != nil {
		return err
	}

	if o.outputFormat == "json" {
		encoder := json.NewEncoder(o.io.StdOut)
		encoder.SetIndent("", "  ")
		return encoder.Encode(sa)
	}

	_, err = fmt.Fprintf(o.io.StdOut, "Created service account %d (%s)\n", sa.ID, sa.UserName)
	return err
}
