// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/gitlab-org/cli/pkg/git_mock (interfaces: GitInterface)
//
// Generated by this command:
//
//	mockgen -typed -destination=./git_interface_mock_for_test.go -package=git_mock gitlab.com/gitlab-org/cli/pkg/git_mock GitInterface
//

// Package git_mock is a generated GoMock package.
package git_mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitInterface is a mock of GitInterface interface.
type MockGitInterface struct {
	ctrl     *gomock.Controller
	recorder *MockGitInterfaceMockRecorder
}

// MockGitInterfaceMockRecorder is the mock recorder for MockGitInterface.
type MockGitInterfaceMockRecorder struct {
	mock *MockGitInterface
}

// NewMockGitInterface creates a new mock instance.
func NewMockGitInterface(ctrl *gomock.Controller) *MockGitInterface {
	mock := &MockGitInterface{ctrl: ctrl}
	mock.recorder = &MockGitInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitInterface) EXPECT() *MockGitInterfaceMockRecorder {
	return m.recorder
}

// AddRemote mocks base method.
func (m *MockGitInterface) AddRemote(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRemote", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRemote indicates an expected call of AddRemote.
func (mr *MockGitInterfaceMockRecorder) AddRemote(arg0, arg1 any) *MockGitInterfaceAddRemoteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRemote", reflect.TypeOf((*MockGitInterface)(nil).AddRemote), arg0, arg1)
	return &MockGitInterfaceAddRemoteCall{Call: call}
}

// MockGitInterfaceAddRemoteCall wrap *gomock.Call
type MockGitInterfaceAddRemoteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceAddRemoteCall) Return(arg0 error) *MockGitInterfaceAddRemoteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceAddRemoteCall) Do(f func(string, string) error) *MockGitInterfaceAddRemoteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceAddRemoteCall) DoAndReturn(f func(string, string) error) *MockGitInterfaceAddRemoteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckoutBranch mocks base method.
func (m *MockGitInterface) CheckoutBranch(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutBranch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutBranch indicates an expected call of CheckoutBranch.
func (mr *MockGitInterfaceMockRecorder) CheckoutBranch(arg0 any) *MockGitInterfaceCheckoutBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutBranch", reflect.TypeOf((*MockGitInterface)(nil).CheckoutBranch), arg0)
	return &MockGitInterfaceCheckoutBranchCall{Call: call}
}

// MockGitInterfaceCheckoutBranchCall wrap *gomock.Call
type MockGitInterfaceCheckoutBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceCheckoutBranchCall) Return(arg0 error) *MockGitInterfaceCheckoutBranchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceCheckoutBranchCall) Do(f func(string) error) *MockGitInterfaceCheckoutBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceCheckoutBranchCall) DoAndReturn(f func(string) error) *MockGitInterfaceCheckoutBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CheckoutNewBranch mocks base method.
func (m *MockGitInterface) CheckoutNewBranch(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckoutNewBranch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckoutNewBranch indicates an expected call of CheckoutNewBranch.
func (mr *MockGitInterfaceMockRecorder) CheckoutNewBranch(arg0 any) *MockGitInterfaceCheckoutNewBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckoutNewBranch", reflect.TypeOf((*MockGitInterface)(nil).CheckoutNewBranch), arg0)
	return &MockGitInterfaceCheckoutNewBranchCall{Call: call}
}

// MockGitInterfaceCheckoutNewBranchCall wrap *gomock.Call
type MockGitInterfaceCheckoutNewBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceCheckoutNewBranchCall) Return(arg0 error) *MockGitInterfaceCheckoutNewBranchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceCheckoutNewBranchCall) Do(f func(string) error) *MockGitInterfaceCheckoutNewBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceCheckoutNewBranchCall) DoAndReturn(f func(string) error) *MockGitInterfaceCheckoutNewBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitBody mocks base method.
func (m *MockGitInterface) CommitBody(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitBody", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitBody indicates an expected call of CommitBody.
func (mr *MockGitInterfaceMockRecorder) CommitBody(arg0 any) *MockGitInterfaceCommitBodyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitBody", reflect.TypeOf((*MockGitInterface)(nil).CommitBody), arg0)
	return &MockGitInterfaceCommitBodyCall{Call: call}
}

// MockGitInterfaceCommitBodyCall wrap *gomock.Call
type MockGitInterfaceCommitBodyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceCommitBodyCall) Return(arg0 string, arg1 error) *MockGitInterfaceCommitBodyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceCommitBodyCall) Do(f func(string) (string, error)) *MockGitInterfaceCommitBodyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceCommitBodyCall) DoAndReturn(f func(string) (string, error)) *MockGitInterfaceCommitBodyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Commits mocks base method.
func (m *MockGitInterface) Commits(arg0, arg1 string) ([]*Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commits", arg0, arg1)
	ret0, _ := ret[0].([]*Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commits indicates an expected call of Commits.
func (mr *MockGitInterfaceMockRecorder) Commits(arg0, arg1 any) *MockGitInterfaceCommitsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commits", reflect.TypeOf((*MockGitInterface)(nil).Commits), arg0, arg1)
	return &MockGitInterfaceCommitsCall{Call: call}
}

// MockGitInterfaceCommitsCall wrap *gomock.Call
type MockGitInterfaceCommitsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceCommitsCall) Return(arg0 []*Commit, arg1 error) *MockGitInterfaceCommitsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceCommitsCall) Do(f func(string, string) ([]*Commit, error)) *MockGitInterfaceCommitsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceCommitsCall) DoAndReturn(f func(string, string) ([]*Commit, error)) *MockGitInterfaceCommitsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Config mocks base method.
func (m *MockGitInterface) Config(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockGitInterfaceMockRecorder) Config(arg0 any) *MockGitInterfaceConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockGitInterface)(nil).Config), arg0)
	return &MockGitInterfaceConfigCall{Call: call}
}

// MockGitInterfaceConfigCall wrap *gomock.Call
type MockGitInterfaceConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceConfigCall) Return(arg0 string, arg1 error) *MockGitInterfaceConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceConfigCall) Do(f func(string) (string, error)) *MockGitInterfaceConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceConfigCall) DoAndReturn(f func(string) (string, error)) *MockGitInterfaceConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CurrentBranch mocks base method.
func (m *MockGitInterface) CurrentBranch() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentBranch")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentBranch indicates an expected call of CurrentBranch.
func (mr *MockGitInterfaceMockRecorder) CurrentBranch() *MockGitInterfaceCurrentBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentBranch", reflect.TypeOf((*MockGitInterface)(nil).CurrentBranch))
	return &MockGitInterfaceCurrentBranchCall{Call: call}
}

// MockGitInterfaceCurrentBranchCall wrap *gomock.Call
type MockGitInterfaceCurrentBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceCurrentBranchCall) Return(arg0 string, arg1 error) *MockGitInterfaceCurrentBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceCurrentBranchCall) Do(f func() (string, error)) *MockGitInterfaceCurrentBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceCurrentBranchCall) DoAndReturn(f func() (string, error)) *MockGitInterfaceCurrentBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteLocalBranch mocks base method.
func (m *MockGitInterface) DeleteLocalBranch(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLocalBranch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLocalBranch indicates an expected call of DeleteLocalBranch.
func (mr *MockGitInterfaceMockRecorder) DeleteLocalBranch(arg0 any) *MockGitInterfaceDeleteLocalBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLocalBranch", reflect.TypeOf((*MockGitInterface)(nil).DeleteLocalBranch), arg0)
	return &MockGitInterfaceDeleteLocalBranchCall{Call: call}
}

// MockGitInterfaceDeleteLocalBranchCall wrap *gomock.Call
type MockGitInterfaceDeleteLocalBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceDeleteLocalBranchCall) Return(arg0 error) *MockGitInterfaceDeleteLocalBranchCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceDeleteLocalBranchCall) Do(f func(string) error) *MockGitInterfaceDeleteLocalBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceDeleteLocalBranchCall) DoAndReturn(f func(string) error) *MockGitInterfaceDeleteLocalBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAllConfig mocks base method.
func (m *MockGitInterface) GetAllConfig(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllConfig", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllConfig indicates an expected call of GetAllConfig.
func (mr *MockGitInterfaceMockRecorder) GetAllConfig(arg0 any) *MockGitInterfaceGetAllConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllConfig", reflect.TypeOf((*MockGitInterface)(nil).GetAllConfig), arg0)
	return &MockGitInterfaceGetAllConfigCall{Call: call}
}

// MockGitInterfaceGetAllConfigCall wrap *gomock.Call
type MockGitInterfaceGetAllConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceGetAllConfigCall) Return(arg0 []byte, arg1 error) *MockGitInterfaceGetAllConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceGetAllConfigCall) Do(f func(string) ([]byte, error)) *MockGitInterfaceGetAllConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceGetAllConfigCall) DoAndReturn(f func(string) ([]byte, error)) *MockGitInterfaceGetAllConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetDefaultBranch mocks base method.
func (m *MockGitInterface) GetDefaultBranch(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultBranch", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultBranch indicates an expected call of GetDefaultBranch.
func (mr *MockGitInterfaceMockRecorder) GetDefaultBranch(arg0 any) *MockGitInterfaceGetDefaultBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultBranch", reflect.TypeOf((*MockGitInterface)(nil).GetDefaultBranch), arg0)
	return &MockGitInterfaceGetDefaultBranchCall{Call: call}
}

// MockGitInterfaceGetDefaultBranchCall wrap *gomock.Call
type MockGitInterfaceGetDefaultBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceGetDefaultBranchCall) Return(arg0 string, arg1 error) *MockGitInterfaceGetDefaultBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceGetDefaultBranchCall) Do(f func(string) (string, error)) *MockGitInterfaceGetDefaultBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceGetDefaultBranchCall) DoAndReturn(f func(string) (string, error)) *MockGitInterfaceGetDefaultBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRemoteURL mocks base method.
func (m *MockGitInterface) GetRemoteURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteURL indicates an expected call of GetRemoteURL.
func (mr *MockGitInterfaceMockRecorder) GetRemoteURL(arg0 any) *MockGitInterfaceGetRemoteURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteURL", reflect.TypeOf((*MockGitInterface)(nil).GetRemoteURL), arg0)
	return &MockGitInterfaceGetRemoteURLCall{Call: call}
}

// MockGitInterfaceGetRemoteURLCall wrap *gomock.Call
type MockGitInterfaceGetRemoteURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceGetRemoteURLCall) Return(arg0 string, arg1 error) *MockGitInterfaceGetRemoteURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceGetRemoteURLCall) Do(f func(string) (string, error)) *MockGitInterfaceGetRemoteURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceGetRemoteURLCall) DoAndReturn(f func(string) (string, error)) *MockGitInterfaceGetRemoteURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GitUserName mocks base method.
func (m *MockGitInterface) GitUserName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GitUserName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GitUserName indicates an expected call of GitUserName.
func (mr *MockGitInterfaceMockRecorder) GitUserName() *MockGitInterfaceGitUserNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GitUserName", reflect.TypeOf((*MockGitInterface)(nil).GitUserName))
	return &MockGitInterfaceGitUserNameCall{Call: call}
}

// MockGitInterfaceGitUserNameCall wrap *gomock.Call
type MockGitInterfaceGitUserNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceGitUserNameCall) Return(arg0 string, arg1 error) *MockGitInterfaceGitUserNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceGitUserNameCall) Do(f func() (string, error)) *MockGitInterfaceGitUserNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceGitUserNameCall) DoAndReturn(f func() (string, error)) *MockGitInterfaceGitUserNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// HasLocalBranch mocks base method.
func (m *MockGitInterface) HasLocalBranch(arg0 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasLocalBranch", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasLocalBranch indicates an expected call of HasLocalBranch.
func (mr *MockGitInterfaceMockRecorder) HasLocalBranch(arg0 any) *MockGitInterfaceHasLocalBranchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasLocalBranch", reflect.TypeOf((*MockGitInterface)(nil).HasLocalBranch), arg0)
	return &MockGitInterfaceHasLocalBranchCall{Call: call}
}

// MockGitInterfaceHasLocalBranchCall wrap *gomock.Call
type MockGitInterfaceHasLocalBranchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceHasLocalBranchCall) Return(arg0 bool, arg1 error) *MockGitInterfaceHasLocalBranchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceHasLocalBranchCall) Do(f func(string) (bool, error)) *MockGitInterfaceHasLocalBranchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceHasLocalBranchCall) DoAndReturn(f func(string) (bool, error)) *MockGitInterfaceHasLocalBranchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LatestCommit mocks base method.
func (m *MockGitInterface) LatestCommit(arg0 string) (*Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestCommit", arg0)
	ret0, _ := ret[0].(*Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestCommit indicates an expected call of LatestCommit.
func (mr *MockGitInterfaceMockRecorder) LatestCommit(arg0 any) *MockGitInterfaceLatestCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestCommit", reflect.TypeOf((*MockGitInterface)(nil).LatestCommit), arg0)
	return &MockGitInterfaceLatestCommitCall{Call: call}
}

// MockGitInterfaceLatestCommitCall wrap *gomock.Call
type MockGitInterfaceLatestCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceLatestCommitCall) Return(arg0 *Commit, arg1 error) *MockGitInterfaceLatestCommitCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceLatestCommitCall) Do(f func(string) (*Commit, error)) *MockGitInterfaceLatestCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceLatestCommitCall) DoAndReturn(f func(string) (*Commit, error)) *MockGitInterfaceLatestCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRemotes mocks base method.
func (m *MockGitInterface) ListRemotes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemotes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemotes indicates an expected call of ListRemotes.
func (mr *MockGitInterfaceMockRecorder) ListRemotes() *MockGitInterfaceListRemotesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemotes", reflect.TypeOf((*MockGitInterface)(nil).ListRemotes))
	return &MockGitInterfaceListRemotesCall{Call: call}
}

// MockGitInterfaceListRemotesCall wrap *gomock.Call
type MockGitInterfaceListRemotesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceListRemotesCall) Return(arg0 []string, arg1 error) *MockGitInterfaceListRemotesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceListRemotesCall) Do(f func() ([]string, error)) *MockGitInterfaceListRemotesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceListRemotesCall) DoAndReturn(f func() ([]string, error)) *MockGitInterfaceListRemotesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Push mocks base method.
func (m *MockGitInterface) Push(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockGitInterfaceMockRecorder) Push(arg0, arg1 any) *MockGitInterfacePushCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockGitInterface)(nil).Push), arg0, arg1)
	return &MockGitInterfacePushCall{Call: call}
}

// MockGitInterfacePushCall wrap *gomock.Call
type MockGitInterfacePushCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfacePushCall) Return(arg0 error) *MockGitInterfacePushCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfacePushCall) Do(f func(string, string) error) *MockGitInterfacePushCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfacePushCall) DoAndReturn(f func(string, string) error) *MockGitInterfacePushCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoteBranchExists mocks base method.
func (m *MockGitInterface) RemoteBranchExists(arg0, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteBranchExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteBranchExists indicates an expected call of RemoteBranchExists.
func (mr *MockGitInterfaceMockRecorder) RemoteBranchExists(arg0, arg1 any) *MockGitInterfaceRemoteBranchExistsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteBranchExists", reflect.TypeOf((*MockGitInterface)(nil).RemoteBranchExists), arg0, arg1)
	return &MockGitInterfaceRemoteBranchExistsCall{Call: call}
}

// MockGitInterfaceRemoteBranchExistsCall wrap *gomock.Call
type MockGitInterfaceRemoteBranchExistsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceRemoteBranchExistsCall) Return(arg0 bool, arg1 error) *MockGitInterfaceRemoteBranchExistsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceRemoteBranchExistsCall) Do(f func(string, string) (bool, error)) *MockGitInterfaceRemoteBranchExistsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceRemoteBranchExistsCall) DoAndReturn(f func(string, string) (bool, error)) *MockGitInterfaceRemoteBranchExistsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetConfig mocks base method.
func (m *MockGitInterface) SetConfig(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetConfig", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetConfig indicates an expected call of SetConfig.
func (mr *MockGitInterfaceMockRecorder) SetConfig(arg0, arg1 any) *MockGitInterfaceSetConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfig", reflect.TypeOf((*MockGitInterface)(nil).SetConfig), arg0, arg1)
	return &MockGitInterfaceSetConfigCall{Call: call}
}

// MockGitInterfaceSetConfigCall wrap *gomock.Call
type MockGitInterfaceSetConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceSetConfigCall) Return(arg0 error) *MockGitInterfaceSetConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceSetConfigCall) Do(f func(string, string) error) *MockGitInterfaceSetConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceSetConfigCall) DoAndReturn(f func(string, string) error) *MockGitInterfaceSetConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRemoteConfig mocks base method.
func (m *MockGitInterface) SetRemoteConfig(arg0, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteConfig", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRemoteConfig indicates an expected call of SetRemoteConfig.
func (mr *MockGitInterfaceMockRecorder) SetRemoteConfig(arg0, arg1, arg2 any) *MockGitInterfaceSetRemoteConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteConfig", reflect.TypeOf((*MockGitInterface)(nil).SetRemoteConfig), arg0, arg1, arg2)
	return &MockGitInterfaceSetRemoteConfigCall{Call: call}
}

// MockGitInterfaceSetRemoteConfigCall wrap *gomock.Call
type MockGitInterfaceSetRemoteConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceSetRemoteConfigCall) Return(arg0 error) *MockGitInterfaceSetRemoteConfigCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceSetRemoteConfigCall) Do(f func(string, string, string) error) *MockGitInterfaceSetRemoteConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceSetRemoteConfigCall) DoAndReturn(f func(string, string, string) error) *MockGitInterfaceSetRemoteConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetRemoteResolution mocks base method.
func (m *MockGitInterface) SetRemoteResolution(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteResolution", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRemoteResolution indicates an expected call of SetRemoteResolution.
func (mr *MockGitInterfaceMockRecorder) SetRemoteResolution(arg0, arg1 any) *MockGitInterfaceSetRemoteResolutionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteResolution", reflect.TypeOf((*MockGitInterface)(nil).SetRemoteResolution), arg0, arg1)
	return &MockGitInterfaceSetRemoteResolutionCall{Call: call}
}

// MockGitInterfaceSetRemoteResolutionCall wrap *gomock.Call
type MockGitInterfaceSetRemoteResolutionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceSetRemoteResolutionCall) Return(arg0 error) *MockGitInterfaceSetRemoteResolutionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceSetRemoteResolutionCall) Do(f func(string, string) error) *MockGitInterfaceSetRemoteResolutionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceSetRemoteResolutionCall) DoAndReturn(f func(string, string) error) *MockGitInterfaceSetRemoteResolutionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetUpstream mocks base method.
func (m *MockGitInterface) SetUpstream(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUpstream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUpstream indicates an expected call of SetUpstream.
func (mr *MockGitInterfaceMockRecorder) SetUpstream(arg0, arg1 any) *MockGitInterfaceSetUpstreamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUpstream", reflect.TypeOf((*MockGitInterface)(nil).SetUpstream), arg0, arg1)
	return &MockGitInterfaceSetUpstreamCall{Call: call}
}

// MockGitInterfaceSetUpstreamCall wrap *gomock.Call
type MockGitInterfaceSetUpstreamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceSetUpstreamCall) Return(arg0 error) *MockGitInterfaceSetUpstreamCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceSetUpstreamCall) Do(f func(string, string) error) *MockGitInterfaceSetUpstreamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceSetUpstreamCall) DoAndReturn(f func(string, string) error) *MockGitInterfaceSetUpstreamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ShowRefs mocks base method.
func (m *MockGitInterface) ShowRefs(arg0 ...string) ([]Ref, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ShowRefs", varargs...)
	ret0, _ := ret[0].([]Ref)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowRefs indicates an expected call of ShowRefs.
func (mr *MockGitInterfaceMockRecorder) ShowRefs(arg0 ...any) *MockGitInterfaceShowRefsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowRefs", reflect.TypeOf((*MockGitInterface)(nil).ShowRefs), arg0...)
	return &MockGitInterfaceShowRefsCall{Call: call}
}

// MockGitInterfaceShowRefsCall wrap *gomock.Call
type MockGitInterfaceShowRefsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceShowRefsCall) Return(arg0 []Ref, arg1 error) *MockGitInterfaceShowRefsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceShowRefsCall) Do(f func(...string) ([]Ref, error)) *MockGitInterfaceShowRefsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceShowRefsCall) DoAndReturn(f func(...string) ([]Ref, error)) *MockGitInterfaceShowRefsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UncommittedChangeCount mocks base method.
func (m *MockGitInterface) UncommittedChangeCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UncommittedChangeCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UncommittedChangeCount indicates an expected call of UncommittedChangeCount.
func (mr *MockGitInterfaceMockRecorder) UncommittedChangeCount() *MockGitInterfaceUncommittedChangeCountCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UncommittedChangeCount", reflect.TypeOf((*MockGitInterface)(nil).UncommittedChangeCount))
	return &MockGitInterfaceUncommittedChangeCountCall{Call: call}
}

// MockGitInterfaceUncommittedChangeCountCall wrap *gomock.Call
type MockGitInterfaceUncommittedChangeCountCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitInterfaceUncommittedChangeCountCall) Return(arg0 int, arg1 error) *MockGitInterfaceUncommittedChangeCountCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitInterfaceUncommittedChangeCountCall) Do(f func() (int, error)) *MockGitInterfaceUncommittedChangeCountCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitInterfaceUncommittedChangeCountCall) DoAndReturn(f func() (int, error)) *MockGitInterfaceUncommittedChangeCountCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
