// Code generated by gen/main.go. DO NOT EDIT.
// Check the internal/config/Readme.md on how to add or modify the config stub.

package config

import (
	"gopkg.in/yaml.v3"
)

func rootConfig() *yaml.Node {
	return &yaml.Node{
		Kind: yaml.DocumentNode,
		Content: []*yaml.Node{
			{
				Kind: yaml.MappingNode,
				Content: []*yaml.Node{
					{
						HeadComment: "# What protocol to use when performing Git operations. Supported values: ssh, https.",
						Kind:        yaml.ScalarNode,
						Value:       "git_protocol",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "ssh",
					},
					{
						HeadComment: "# What editor glab should run when creating issues, merge requests, etc. This global config cannot be overridden by hostname.",
						Kind:        yaml.ScalarNode,
						Value:       "editor",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# What browser glab should run when opening links. This global config cannot be overridden by hostname.",
						Kind:        yaml.ScalarNode,
						Value:       "browser",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles",
						Kind:        yaml.ScalarNode,
						Value:       "glamour_style",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "dark",
					},
					{
						HeadComment: "# Allow glab to automatically check for updates and notify you when there are new updates.",
						Kind:        yaml.ScalarNode,
						Value:       "check_update",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "true",
					},
					{
						HeadComment: "# Last update check timestamp, used for checking when the last update check was performed.",
						Kind:        yaml.ScalarNode,
						Value:       "last_update_check_timestamp",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.",
						Kind:        yaml.ScalarNode,
						Value:       "display_hyperlinks",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "false",
					},
					{
						HeadComment: "# Default GitLab hostname to use.",
						Kind:        yaml.ScalarNode,
						Value:       "host",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "gitlab.com",
					},
					{
						HeadComment: "# Set to true (1) to disable prompts, or false (0) to enable them.",
						Kind:        yaml.ScalarNode,
						Value:       "no_prompt",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "false",
					},
					{
						HeadComment: "# Set to false (0) to disable sending usage data to your GitLab instance or true (1) to enable.\n# See https://docs.gitlab.com/administration/settings/usage_statistics/\n# for more information",
						Kind:        yaml.ScalarNode,
						Value:       "telemetry",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "true",
					},
					{
						HeadComment: "# Automatically run GitLab Duo CLI without prompting (true/false). Set to true to skip the confirmation prompt.",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_auto_run",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Automatically download Duo CLI binary without prompting (true/false).",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_auto_download",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Path to the installed Duo CLI binary (automatically set). Default: ~/.config/glab-cli/bin/duo",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_binary_path",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Version of the installed Duo CLI binary (automatically set).",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_binary_version",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# SHA256 checksum of the installed Duo CLI binary (automatically set).",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_binary_checksum",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Last time an update check was performed (automatically set).",
						Kind:        yaml.ScalarNode,
						Value:       "duo_cli_last_update_check",
					},
					{
						Kind:  yaml.ScalarNode,
						Value: "",
					},
					{
						HeadComment: "# Configuration specific for GitLab instances.",
						Kind:        yaml.ScalarNode,
						Value:       "hosts",
					},
					{
						Kind: yaml.MappingNode,
						Content: []*yaml.Node{
							{
								Kind:  yaml.ScalarNode,
								Value: "gitlab.com",
							},
							{
								Kind: yaml.MappingNode,
								Content: []*yaml.Node{
									{
										HeadComment: "# What protocol to use to access the API endpoint. Supported values: http, https.",
										Kind:        yaml.ScalarNode,
										Value:       "api_protocol",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "https",
									},
									{
										HeadComment: "# Configure host for API endpoint. Defaults to the host itself.",
										Kind:        yaml.ScalarNode,
										Value:       "api_host",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "gitlab.com",
									},
									{
										HeadComment: "# Subfolder where GitLab is installed (e.g., 'gitlab' for https://example.com/gitlab/)\n# Use this when GitLab is hosted at a subfolder rather than domain root.\n# Supports nested paths (e.g., 'apps/gitlab' for https://example.com/apps/gitlab/)\n# Slashes are automatically trimmed, so 'gitlab', '/gitlab', and 'gitlab/' are equivalent.\n# Only applies to HTTP/HTTPS operations (API and git clone).",
										Kind:        yaml.ScalarNode,
										Value:       "subfolder",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "",
									},
									{
										HeadComment: "# Alternate hostname for SSH git operations (e.g., 'ssh.example.com' or 'git.example.com')\n# Use this when SSH uses a different hostname than HTTP/API operations.\n# Only affects SSH cloning and git operations.",
										Kind:        yaml.ScalarNode,
										Value:       "ssh_host",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "",
									},
									{
										HeadComment: "# Your GitLab access token. To get one, read https://docs.gitlab.com/user/profile/personal_access_tokens/",
										Kind:        yaml.ScalarNode,
										Value:       "token",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "",
									},
									{
										HeadComment: "# Custom proxy for this host. Overrides environment proxy settings when set.",
										Kind:        yaml.ScalarNode,
										Value:       "proxy",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "",
									},
									{
										HeadComment: "# The domains of associated container registries. These are used to configure the\n# Docker credential helper.",
										Kind:        yaml.ScalarNode,
										Value:       "container_registry_domains",
									},
									{
										Kind:  yaml.ScalarNode,
										Value: "gitlab.com,gitlab.com:443,registry.gitlab.com",
									},
									{
										HeadComment: "# Custom HTTP headers to add to all HTTP requests made by glab. Supports both direct values and environment variable loading.\n# - name: Proxy-Authorization\n#   value: Bearer token123\n# - name: Cf-Access-Client-Secret\n#   valueFromEnv: MY_SECRET_VALUE",
										Kind:        yaml.ScalarNode,
										Value:       "custom_headers",
									},
									{
										Kind:  yaml.SequenceNode,
										Value: "",
									},
								},
							},
						},
					},
					{
						HeadComment: "# Use aliases to create nicknames for glab commands. Supports shell-executable aliases that may not be glab commands.",
						Kind:        yaml.ScalarNode,
						Value:       "aliases",
					},
					{
						Kind: yaml.MappingNode,
						Content: []*yaml.Node{
							{
								Kind:  yaml.ScalarNode,
								Value: "ci",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "pipeline ci",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "co",
							},
							{
								Kind:  yaml.ScalarNode,
								Value: "mr checkout",
							},
						},
					},
				},
			},
		},
	}
}
